# Generated by Django 5.1.2 on 2024-10-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_carrinho_carrinhoitem'),
        ('loja', '0002_cliente'),
    ]

    operations = [
    ]
