# Generated by Django 5.1.2 on 2024-12-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_area_produto_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='Pass@2023', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
